site_name: HOMEd Wiki 2.0
repo_url: https://github.com/u236/homed-docs/

extra_css:
  - /assets/css/extra.css

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true

theme:

  name: material
  logo: /assets/images/homed.svg

  palette:

    - media: "(prefers-color-scheme)"
      primary: black
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - content.code.copy
